version: "3"

services:
  sherlock-db-service-dataset:
    build:
      context: ./backend/sherlock-db-service-dataset
      dockerfile: Dockerfile
    image: sherlock-db-service-dataset-production

  sherlock-db-instance-dataset:
    image: mongo:4
    volumes:
      - "./backend/db-instance-dataset/data/db/dataset:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=dataset
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  sherlock-db-instance-fragment:
    image: postgres:14
    volumes:
      - "./backend/db-instance-fragment/data/db/fragment:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fragment
    ports:
      - "5432:5432"

  sherlock-db-instance-statistics:
    image: mongo:4
    volumes:
      - "./backend/db-instance-statistics/data/db/statistics:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=statistics
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password