version: "3"

services:
  webcase-db-instance-nmrshiftdb-dataset:
    image: mongo:4
    volumes:
      - "./backend/db-instance-nmrshiftdb-dataset/data/db/nmrshiftdb-dataset:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=nmrshiftdb-dataset
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  webcase-db-instance-nmrshiftdb-hybridization:
    image: mongo:4
    volumes:
      - "./backend/db-instance-nmrshiftdb-hybridization/data/db/nmrshiftdb-hybridization:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=nmrshiftdb-hybridization
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  webcase-db-instance-result:
    volumes:
      - "./backend/db-instance-result/data/db/result:/data/db"

  webcase-db-instance-hosecode:
    image: mongo:4
    volumes:
      - "./backend/db-instance-hosecode/data/db/hosecode:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=hosecode
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password