version: "3"

services:
  webcase-db-instance-dataset:
    image: mongo:4
    volumes:
      - "./backend/db-instance-dataset/data/db/dataset:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=dataset
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  webcase-db-instance-statistics:
    image: mongo:4
    volumes:
      - "./backend/db-instance-statistics/data/db/statistics:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=statistics
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  webcase-db-instance-result:
    volumes:
      - "./backend/db-instance-result/data/db/result:/data/db"

  webcase-db-instance-hosecode:
    image: mongo:4
    volumes:
      - "./backend/db-instance-hosecode/data/db/hosecode:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=hosecode
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password