version: "3"

volumes:
  hosecode-file-storage:
    driver: local

services:
  webcase-discovery-server:
    container_name: webcase-discovery-server
    build:
      context: ./backend/webcase-discovery-server
      dockerfile: Dockerfile
    image: michaelwenk/webcase-discovery-server
    ports:
      - "8761:8761"

  webcase-gateway:
    container_name: webcase-gateway
    build:
      context: ./backend/webcase-gateway
      dockerfile: Dockerfile
    image: michaelwenk/webcase-gateway
    ports:
      - "8081:8080"
    depends_on:
      - webcase-discovery-server

  webcase-core:
    container_name: webcase-core
    build:
      context: ./backend/webcase-core
      dockerfile: Dockerfile
    image: michaelwenk/webcase-core
    ports:
      - "8082:8080"
    depends_on:
      - webcase-discovery-server

  webcase-pylsd:
    container_name: webcase-pylsd
    build:
      context: ./backend/webcase-pylsd
      dockerfile: Dockerfile
    image: michaelwenk/webcase-pylsd
    ports:
      - "8083:8080"
    depends_on:
      - webcase-discovery-server
      - webcase-db-service-hosecode
    volumes:
    - hosecode-file-storage:/data/hosecode

  webcase-db-service-dataset:
    container_name: webcase-db-service-dataset
    ports:
      - "8087:8080"
    depends_on:
      - webcase-discovery-server
      - webcase-db-instance-dataset

  webcase-db-service-statistics:
    container_name: webcase-db-service-statistics
    build:
      context: ./backend/webcase-db-service-statistics
      dockerfile: Dockerfile
    image: michaelwenk/webcase-db-service-statistics
    ports:
      - "8088:8080"
    depends_on:
      - webcase-discovery-server
      - webcase-db-instance-statistics

  webcase-db-service-result:
    container_name: webcase-db-service-result
    build:
      context: ./backend/webcase-db-service-result
      dockerfile: Dockerfile
    image: michaelwenk/webcase-db-service-result
    ports:
      - "8089:8080"
    depends_on:
      - webcase-discovery-server
      - webcase-db-instance-result

  webcase-db-service-hosecode:
    container_name: webcase-db-service-hosecode
    build:
      context: ./backend/webcase-db-service-hosecode
      dockerfile: Dockerfile
    image: michaelwenk/webcase-db-service-hosecode
    ports:
      - "8091:8080"
    depends_on:
      - webcase-discovery-server
      - webcase-db-instance-hosecode
    volumes:
    - hosecode-file-storage:/data/hosecode

  webcase-db-instance-dataset:
    container_name: webcase-db-instance-dataset
    ports:
      - 27020:27017

  webcase-db-instance-statistics:
    container_name: webcase-db-instance-statistics
    ports:
      - 27021:27017

  webcase-db-instance-result:
    image: mongo:4
    container_name: webcase-db-instance-result
    ports:
      - 27022:27017
    environment:
      - MONGO_INITDB_DATABASE=result
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  webcase-db-instance-hosecode:
    image: mongo:4
    container_name: webcase-db-instance-hosecode
    ports:
      - 27023:27017
    environment:
      - MONGO_INITDB_DATABASE=hosecode
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password