version: "3"

services:

  sherlock-db-service-dataset:
    build:
      context: ./backend/sherlock-db-service-dataset
      dockerfile: Dockerfile.publish
    image: michaelwenk/sherlock-db-service-dataset

  sherlock-db-instance-dataset:
    image: michaelwenk/sherlock-db-instance-dataset
    build:
      context: backend/db-instance-dataset
      dockerfile: Dockerfile.publish

  sherlock-db-instance-statistics:
    image: michaelwenk/sherlock-db-instance-statistics
    build:
      context: backend/db-instance-statistics
      dockerfile: Dockerfile.publish

  sherlock-db-instance-hosecode:
    image: michaelwenk/sherlock-db-instance-hosecode
    build:
      context: backend/db-instance-hosecode
      dockerfile: Dockerfile.publish