version: "3"

services:
  sherlock-db-service-dataset:
    build:
      context: ./backend/sherlock-db-service-dataset
      dockerfile: Dockerfile
    image: sherlock-db-service-dataset-production

  sherlock-db-service-hosecode:
    container_name: sherlock-db-service-hosecode
    build:
      context: ./backend/sherlock-db-service-hosecode
      dockerfile: Dockerfile
    image: michaelwenk/sherlock-db-service-hosecode
    ports:
      - "8091:8080"
    depends_on:
      - sherlock-discovery-server
      - sherlock-db-instance-hosecode
    volumes:
      - hosecode-file-storage:/data/hosecode

  sherlock-db-instance-dataset:
    image: mongo:4
    volumes:
      - "./backend/db-instance-dataset/data/db/dataset:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=dataset
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  sherlock-db-instance-statistics:
    image: mongo:4
    volumes:
      - "./backend/db-instance-statistics/data/db/statistics:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=statistics
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  sherlock-db-instance-result:
    volumes:
      - "./backend/db-instance-result/data/db/result:/data/db"

  sherlock-db-instance-hosecode:
    image: mongo:4
    container_name: sherlock-db-instance-hosecode
    ports:
      - 27023:27017
    volumes:
      - "./backend/db-instance-hosecode/data/db/hosecode:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=hosecode
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password