version: "3"

services:
  webcase-discovery-server:
    container_name: webcase-discovery-server
    build:
      context: ./backend/webcase-discovery-server
      dockerfile: Dockerfile
    image: michaelwenk/webcase-discovery-server
    ports:
      - "8761:8761"

  webcase-gateway:
    container_name: webcase-gateway
    build:
      context: ./backend/webcase-gateway
      dockerfile: Dockerfile
    image: michaelwenk/webcase-gateway
    ports:
      - "8081:8080"
    depends_on:
      - webcase-discovery-server

  webcase-core:
    container_name: webcase-core
    build:
      context: ./backend/webcase-core
      dockerfile: Dockerfile
    image: michaelwenk/webcase-core
    ports:
      - "8082:8080"
    depends_on:
      - webcase-discovery-server

  webcase-dereplication:
    container_name: webcase-dereplication
    build:
      context: ./backend/webcase-dereplication
      dockerfile: Dockerfile
    image: michaelwenk/webcase-dereplication
    ports:
      - "8083:8080"
    depends_on:
      - webcase-discovery-server

  webcase-elucidation:
    container_name: webcase-elucidation
    build:
      context: ./backend/webcase-elucidation
      dockerfile: Dockerfile
    image: michaelwenk/webcase-elucidation
    ports:
      - "8084:8080"
    depends_on:
      - webcase-discovery-server

  webcase-pylsd:
    container_name: webcase-pylsd
    build:
      context: ./backend/webcase-pylsd
      dockerfile: Dockerfile
    image: michaelwenk/webcase-pylsd
    ports:
      - "8085:8080"
    depends_on:
      - webcase-discovery-server

  webcase-result:
    container_name: webcase-result
    build:
      context: ./backend/webcase-result
      dockerfile: Dockerfile
    image: michaelwenk/webcase-result
    ports:
      - "8086:8080"
    depends_on:
      - webcase-discovery-server

  webcase-db-service-dataset:
    container_name: webcase-db-service-dataset
    build:
      context: ./backend/webcase-db-service-dataset
      dockerfile: Dockerfile
    image: michaelwenk/webcase-db-service-dataset
    ports:
      - "8087:8080"
    depends_on:
      - webcase-discovery-server
      - webcase-db-instance-nmrshiftdb-dataset

  webcase-db-service-hybridization:
    container_name: webcase-db-service-hybridization
    build:
      context: ./backend/webcase-db-service-hybridization
      dockerfile: Dockerfile
    image: michaelwenk/webcase-db-service-hybridization
    ports:
      - "8088:8080"
    depends_on:
      - webcase-discovery-server
      - webcase-db-instance-nmrshiftdb-hybridization

  webcase-db-service-result:
    container_name: webcase-db-service-result
    build:
      context: ./backend/webcase-db-service-result
      dockerfile: Dockerfile
    image: michaelwenk/webcase-db-service-result
    ports:
      - "8089:8080"
    depends_on:
      - webcase-discovery-server
      - webcase-db-instance-result

  webcase-casekit:
    container_name: webcase-casekit
    build:
      context: ./backend/webcase-casekit
      dockerfile: Dockerfile
    image: michaelwenk/webcase-casekit
    ports:
      - "8090:8080"
    depends_on:
      - webcase-discovery-server

  webcase-db-service-hosecode:
    container_name: webcase-db-service-hosecode
    build:
      context: ./backend/webcase-db-service-hosecode
      dockerfile: Dockerfile
    image: michaelwenk/webcase-db-service-hosecode
    ports:
      - "8091:8080"
    depends_on:
      - webcase-discovery-server
      - webcase-db-instance-hosecode

  webcase-db-instance-nmrshiftdb-dataset:
    container_name: webcase-db-instance-nmrshiftdb-dataset
    ports:
      - 27020:27017
    restart: always

  webcase-db-instance-nmrshiftdb-hybridization:
    container_name: webcase-db-instance-nmrshiftdb-hybridization
    ports:
      - 27021:27017
    restart: always

  webcase-db-instance-result:
    image: mongo:4
    container_name: webcase-db-instance-result
    ports:
      - 27022:27017
    environment:
      - MONGO_INITDB_DATABASE=result
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always

  webcase-db-instance-hosecode:
    image: mongo:4
    container_name: webcase-db-instance-hosecode
    ports:
      - 27023:27017
    environment:
      - MONGO_INITDB_DATABASE=hosecode
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always