version: "3"

volumes:
  hosecode-file-storage:
    driver: local

services:
  sherlock-discovery-server:
    container_name: sherlock-discovery-server
    build:
      context: ./backend/sherlock-discovery-server
      dockerfile: Dockerfile
    image: michaelwenk/sherlock-discovery-server
    ports:
      - "8761:8761"

  sherlock-gateway:
    container_name: sherlock-gateway
    build:
      context: ./backend/sherlock-gateway
      dockerfile: Dockerfile
    image: michaelwenk/sherlock-gateway
    ports:
      - "8081:8080"
    depends_on:
      - sherlock-discovery-server

  sherlock-core:
    container_name: sherlock-core
    build:
      context: ./backend/sherlock-core
      dockerfile: Dockerfile
    image: michaelwenk/sherlock-core
    ports:
      - "8082:8080"
    depends_on:
      - sherlock-discovery-server
    volumes:
      - hosecode-file-storage:/data/hosecode

  sherlock-db-service-dataset:
    container_name: sherlock-db-service-dataset
    ports:
      - "8087:8080"
    depends_on:
      - sherlock-discovery-server
      - sherlock-db-instance-dataset

  sherlock-db-service-statistics:
    container_name: sherlock-db-service-statistics
    build:
      context: ./backend/sherlock-db-service-statistics
      dockerfile: Dockerfile
    image: michaelwenk/sherlock-db-service-statistics
    ports:
      - "8088:8080"
    depends_on:
      - sherlock-discovery-server
      - sherlock-db-instance-statistics
    volumes:
      - hosecode-file-storage:/data/hosecode

  sherlock-db-service-result:
    container_name: sherlock-db-service-result
    build:
      context: ./backend/sherlock-db-service-result
      dockerfile: Dockerfile
    image: michaelwenk/sherlock-db-service-result
    ports:
      - "8089:8080"
    depends_on:
      - sherlock-discovery-server
      - sherlock-db-instance-result

  sherlock-db-instance-dataset:
    container_name: sherlock-db-instance-dataset
    ports:
      - "27020:27017"
    command:
      --wiredTigerCacheSizeGB 2

  sherlock-db-instance-statistics:
    container_name: sherlock-db-instance-statistics
    ports:
      - "27021:27017"

  sherlock-db-instance-result:
    image: mongo:4
    container_name: sherlock-db-instance-result
    ports:
      - "27022:27017"
    environment:
      - MONGO_INITDB_DATABASE=result
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "./backend/db-instance-result/data/db/result:/data/db"